#datasource config
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yiqing?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
      username: root
      password: 123456
      #连接池配置
      #初始化大小 最大 最小
      initial-size: 5
      max-active: 30
      min-idle: 5
      #连接超时等待时间
      max-wait: 5000
      #连接在池中的最小生存时间 ms
      min-evictable-idle-time-millis: 3000000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置监控统计拦截的Filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      #thymeleaf配置

  thymeleaf:
    prefix: classpath:/templates/
    #开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#端口8081 项目启动路径
server:
  port: 8081
  servlet:
    context-path: /

#mybatis-plus配置
mybatis-plus:
  mapperLocations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1  # 逻辑已删除值
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)
  type-aliases-package: com.demo.dto
  configuration:
    map-underscore-to-camel-case: true
